version: '2'
services:
  zookeeper:
    container_name: messaging-wurstmeister
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka-meniga:
    image: wurstmeister/kafka
    container_name: messaging-kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  rabbitmq:
    image: rabbitmq:3.8.14-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672